name: NeoInvisibleArmor
version: @version@
main: com.neoinvisiblearmor.NeoInvisibleArmor
api-version: 1.16
author: sota70
commands:
  neoinvisiblearmor:
    aliases: nia
    description: "It allows to open Armor GUI"
